allowBuilds:
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  unrs-resolver: true

# backend/pnpm-workspace.yaml
onlyBuiltDependencies:
  - '@prisma/engines'
  - bcrypt
  - prisma
  - unrs-resolver